version: '3'
services:
  oracledb:
    image: truevoly/oracle-12c
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8090:8090
      - 5500:5500