INSERT INTO RECOMMANDATION (TITLE_FR, DESCRIPTION_FR) VALUES ('La SONACOS (Décembre 2019)','Il s''agit de la refonte des structures admnisitratives organisationnelles de telle sorte qu''elle permettra aux différents départements ministériels administratifs, au niveau central et local, d''assurer la mise en oeuvre efficace et performante des politiques publiques et de fournir les services publics en respectant les normes de qualité aux usagers.')



CREATE TABLE MISSIONS (ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1), TITLE_AR VARCHAR2(200), TITLE_FR VARCHAR2(200), DESCRIPTION_AR VARCHAR2(400), DESCRIPTION_FR VARCHAR2(4000)


INSERT INTO RECOMMANDATIONS (TITLE_FR, START_DATE, END_DATE, ESCOMPTE, OBTENU, OBSERVATIONS, RESSOURCES, RESPONSABLE, ACTIONS, CODE, PERCENTAGE, MISSION_ID) VALUES ('');